DELETE FROM season;
DELETE FROM matches;
DELETE FROM club;
DELETE FROM clubStats;
DELETE FROM stats;
DELETE FROM playerStats;
DELETE FROM nation;

/*importing matches for 2010/2011 season*/
.mode "csv"
.separator ","
.import '| tail -n +90 data/11champs.csv' matches

/*importing matches for 2011/2012 season*/
.mode "csv"
.separator ","
.import '| tail -n +90 data/12champs.csv' matches

/*importing matches for 2012/2013 season*/
.mode "csv"
.separator ","
.import '| tail -n +90 data/13champs.csv' matches

/*importing matches for 2013/2014 season*/
.mode "csv"
.separator ","
.import '| tail -n +90 data/14champs.csv' matches

/*importing matches for 2014/2015 season*/
.mode "csv"
.separator ","
.import '| tail -n +92 data/15champs.csv' matches

/*importing matches for 2015/2016 season*/
.mode "csv"
.separator ","
.import '| tail -n +94 data/16champs.csv' matches

/*Data for seasons*/
INSERT INTO seasons VALUES(11, '2010/2011 Season');
INSERT INTO seasons VALUES(12, '2011/2012 Season');
INSERT INTO seasons VALUES(13, '2012/2013 Season');
INSERT INTO seasons VALUES(14, '2013/2014 Season');
INSERT INTO seasons VALUES(15, '2014/2015 Season');
INSERT INTO seasons VALUES(16, '2015/2016 Season');

/*Data for stats*/
INSERT INTO stats VALUES(1, 'Player Stats 2010/2011', 11);
INSERT INTO stats VALUES(2, 'Club Stats 2010/2011', 11);
INSERT INTO stats VALUES(3, 'Player Stats 2011/2012', 12);
INSERT INTO stats VALUES(4, 'Club Stats 2011/2012', 12);
INSERT INTO stats VALUES(5, 'Player Stats 2012/2013', 13);
INSERT INTO stats VALUES(6, 'Club Stats 2012/2013', 13);
INSERT INTO stats VALUES(7, 'Player Stats 2013/2014', 14);
INSERT INTO stats VALUES(8, 'Club Stats 2013/2014', 14);
INSERT INTO stats VALUES(9, 'Player Stats 2014/2015', 15);
INSERT INTO stats VALUES(10, 'Club Stats 2014/2015', 15);
INSERT INTO stats VALUES(11, 'Player Stats 2015/2016', 16);
INSERT INTO stats VALUES(12, 'Club Stats 2015/2016', 16);

/*Data for nation*/
INSERT INTO nation VALUES(1, 'AUSTRIA');
INSERT INTO nation VALUES(2, 'BELARUS');
INSERT INTO nation VALUES(3, 'BELGIUM');
INSERT INTO nation VALUES(4, 'BULGARIA');
INSERT INTO nation VALUES(5, 'CROATIA');
INSERT INTO nation VALUES(6, 'CYPRUS');
INSERT INTO nation VALUES(7, 'CZECH REPUBLIC');
INSERT INTO nation VALUES(8, 'DENMARK');
INSERT INTO nation VALUES(9, 'ENGLAND');
INSERT INTO nation VALUES(10, 'FRANCE');
INSERT INTO nation VALUES(11, 'GERMANY');
INSERT INTO nation VALUES(12, 'GREECE');
INSERT INTO nation VALUES(13, 'ISRAEL');
INSERT INTO nation VALUES(14, 'ITALY');
INSERT INTO nation VALUES(15, 'KAZAKHSTAN');
INSERT INTO nation VALUES(16, 'NETHERLANDS');
INSERT INTO nation VALUES(17, 'PORTUGAL');
INSERT INTO nation VALUES(18, 'ROMANIA');
INSERT INTO nation VALUES(19, 'RUSSIA');
INSERT INTO nation VALUES(20, 'SCOTLAND');
INSERT INTO nation VALUES(21, 'SERBIA');
INSERT INTO nation VALUES(22, 'SLOVAKIA');
INSERT INTO nation VALUES(23, 'SLOVENIA');
INSERT INTO nation VALUES(24, 'SPAIN');
INSERT INTO nation VALUES(25, 'SWEDEN');
INSERT INTO nation VALUES(26, 'SWITZERLAND');
INSERT INTO nation VALUES(27, 'TURKEY');
INSERT INTO nation VALUES(28, 'UKRAINE');

/*Data for club*/
INSERT INTO club VALUES(1, 'AC MILAN', 14);
INSERT INTO club VALUES(2, 'AJAX', 16);
INSERT INTO club VALUES(3, 'APOEL', 6);
INSERT INTO club VALUES(4, 'ANDERLECHT', 3);
INSERT INTO club VALUES(5, 'ARSENAL', 9);
INSERT INTO club VALUES(6, 'ASTANA', 15);
INSERT INTO club VALUES(7, 'ATHLETIC BILBAO', 24);
INSERT INTO club VALUES(8, 'ATLETICO MADRID', 24);
INSERT INTO club VALUES(9, 'AUSTRIA WIEN', 1);
INSERT INTO club VALUES(10, 'AUXERRE', 10);
INSERT INTO club VALUES(11, 'BARCELONA', 24);
INSERT INTO club VALUES(12, 'BASEL', 26);
INSERT INTO club VALUES(13, 'BATE BORISOV', 2);
INSERT INTO club VALUES(14, 'BAYERN MUNICH', 11);
INSERT INTO club VALUES(15, 'BAYER LEVERKUSEN', 11);
INSERT INTO club VALUES(16, 'BENFICA', 17);
INSERT INTO club VALUES(17, 'BORUSSIA DORTMUND', 11);
INSERT INTO club VALUES(18, 'BORUSSIA MONCHENGLADBACH', 1);
INSERT INTO club VALUES(19, 'BRAGA', 17);
INSERT INTO club VALUES(20, 'BURSASPOR', 27);
INSERT INTO club VALUES(21, 'CELTIC', 20);
INSERT INTO club VALUES(22, 'CFR CLUJ', 18);
INSERT INTO club VALUES(23, 'CHELSEA', 9);
INSERT INTO club VALUES(24, 'COPENHAGEN', 8);
INSERT INTO club VALUES(25, 'CSKA MOSCOW', 19);
INSERT INTO club VALUES(26, 'DINAMO ZAGREB', 5);
INSERT INTO club VALUES(27, 'DYNAMO KYIV', 28);
INSERT INTO club VALUES(28, 'GALATASARAY', 27);
INSERT INTO club VALUES(29, 'GENK', 3);
INSERT INTO club VALUES(30, 'GENT', 3);
INSERT INTO club VALUES(31, 'HAPOEL TEL AVIV', 13);
INSERT INTO club VALUES(32, 'JUVENTUS', 14);
INSERT INTO club VALUES(33, 'LILLE', 10);
INSERT INTO club VALUES(34, 'LIVERPOOL', 9);
INSERT INTO club VALUES(35, 'LUDOGORETS RAZGRAD', 4);
INSERT INTO club VALUES(36, 'LYON', 10);
INSERT INTO club VALUES(37, 'INTER MILAN', 14);
INSERT INTO club VALUES(38, 'MACCABI TEL AVIV', 13);
INSERT INTO club VALUES(39, 'MALAGA', 24);
INSERT INTO club VALUES(40, 'MALMO FF', 25);
INSERT INTO club VALUES(41, 'MANCHESTER CITY', 9);
INSERT INTO club VALUES(42, 'MANCHESTER UNITED', 9);
INSERT INTO club VALUES(43, 'MARIBOR', 23);
INSERT INTO club VALUES(44, 'MARSEILLE', 10);
INSERT INTO club VALUES(45, 'MONACO', 10);
INSERT INTO club VALUES(46, 'MONTPELLIER', 10);
INSERT INTO club VALUES(47, 'NAPOLI', 14);
INSERT INTO club VALUES(48, 'NORDSJAELLAND', 8);
INSERT INTO club VALUES(49, 'OLYMPIACOS', 12);
INSERT INTO club VALUES(50, 'OTELUL GALATI', 18);
INSERT INTO club VALUES(51, 'PANATHINAIKOS', 12);
INSERT INTO club VALUES(52, 'PARITZAN', 21);
INSERT INTO club VALUES(53, 'PORTO', 17);
INSERT INTO club VALUES(54, 'PSG', 10);
INSERT INTO club VALUES(55, 'PSV', 16);
INSERT INTO club VALUES(56, 'RANGERS', 20);
INSERT INTO club VALUES(57, 'REAL MADRID', 24);
INSERT INTO club VALUES(58, 'REAL SOLCIEDAD', 24);
INSERT INTO club VALUES(59, 'ROMA', 14);
INSERT INTO club VALUES(60, 'RUBIN KAZAN', 19);
INSERT INTO club VALUES(61, 'SCHALKE 04', 11);
INSERT INTO club VALUES(62, 'SEVILLA', 24);
INSERT INTO club VALUES(63, 'SHAKHTAR DONETSK', 28);
INSERT INTO club VALUES(64, 'SPARTAK MOSCOW', 19);
INSERT INTO club VALUES(65, 'SPORTING CP', 17);
INSERT INTO club VALUES(66, 'STEAUA BUCURESTI', 18);
INSERT INTO club VALUES(67, 'TOTTENHAM', 9);
INSERT INTO club VALUES(68, 'TRABZONSPOR', 27);
INSERT INTO club VALUES(69, 'TWENTE', 16);
INSERT INTO club VALUES(70, 'VALENCIA', 24);
INSERT INTO club VALUES(71, 'VIKTORIA PLZEN', 7);
INSERT INTO club VALUES(72, 'VILLARREAL', 24);
INSERT INTO club VALUES(73, 'WERDER BREMEN', 11);
INSERT INTO club VALUES(74, 'WOLFSBURG', 11);
INSERT INTO club VALUES(75, 'ZENIT', 19);
INSERT INTO club VALUES(76, 'ZILINA', 22);


/*Data for club stats*/
/*INSERT INTO clubStats VALUES(clubkey, gamesplayed, won, tied, lost, goalf for, against, statkey, seeasonkey);*/
INSERT INTO clubStats VALUES('BARCELONA', 13, 9, 3, 1, 0, 0, 0, 2011);
--INSERT INTO clubStats VALUES();


/*Data for player stats*/
--INSERT INTO playerStats VALUES(playerkey, statkey, name, apperances, goals, assists, nation);
INSERT INTO playerStats VALUES(0, 0, 'Messi', 13, 12, 0, 'Argentina');
